
#
# Web (expressjs) settings.
#
web:
  port: 7000
  api: [3, 1]
  upload_storage: memory
  upload_path: "{{work_dir}}/web/upload/{{process_name}}"

#
# DO NOT USE any handlebars template variables (e.g. process_name) in logger
# section because they are never merged.
#
logger:
  rotating_file_stream:
    period: daily
    threshold: 1g     # The maximum size for a log file to reach before it's rotated.
    totalFiles: 60    # Keep 60 days (2 months) of log files.


#
# Transform from DGv1 schema (board_type/board_id/sensor: type) to
# DGv3 schema (p_type/p_id/s_type/s_id: {type1, type2, ...})
#
1to3:
  verbose: false
