
#
# Web (expressjs) settings.
#
web:
  port: 7000
  api: [3, 1]
  upload_storage: memory
  upload_path: "{{work_dir}}/web/upload/{{process_name}}"

#
# DO NOT USE any handlebars template variables (e.g. process_name) in logger
# section because they are never merged.
#
logger:
  rotating_file_stream:
    period: daily
    threshold: 1g     # The maximum size for a log file to reach before it's rotated.
    totalFiles: 60    # Keep 60 days (2 months) of log files.


#
# Transform from DGv1 schema (board_type/board_id/sensor: type) to
# DGv3 schema (p_type/p_id/s_type/s_id: {type1, type2, ...})
#
1to3:
  verbose: false


#
# Legacy REST api for TOE v1.0: `/api/v1/hub/:id/:profile` (POST)
#
webapi-legacy:
  enabled: false


#
# Use `request` module to forward Time-series data points (measurements) to
# next http server. There are 2 ways of using HTTP POST to send these data
# points to next http server:
#
# 1. Send as HTTP body in JSON format without GZ compression.
# 2. Send sa a JSON file in HTTP Form (multiparts) with GZ compression.
#
http-forwarder:
  verbose: false
  destinations:
    - name: test1
      enabled: false
      url: http://localhost:9999/a/b/c
      compressed: false
      health_check: false
      url_append: false
      request_opts:
        auth: {user: 'aaa', password: 'bbbb'}

    - name: test2
      enabled: true
      url: http://localhost:9998/x/y/z
      compressed: true
      matched_profiles: 'foop'
      matched_ids: '*'
      health_check: false
      url_append: true
      request_opts:
        qs: {token: 'XXX'}

    - name: test3
      enabled: false
      url: http://localhost:9998/x/y/z
      compressed: true
      matched_profiles: '*'
      matched_ids: '1803S320005[0-9]'
      health_check: true
      url_append: true
      request_opts:
        qs: {token: 'XXX'}
