
#
# Web (expressjs) settings.
#
web:
  port: 7000
  api: [3, 1]
  upload_storage: memory
  upload_path: "{{work_dir}}/web/upload/{{process_name}}"

#
# DO NOT USE any handlebars template variables (e.g. process_name) in logger
# section because they are never merged.
#
logger:
  rotating_file_stream:
    period: daily
    threshold: 1g     # The maximum size for a log file to reach before it's rotated.
    totalFiles: 60    # Keep 60 days (2 months) of log files.


http-csv:
  verbose: true
  destinations:

    - name: local
      url: http://localhost:7000/next3
      profile-match: '*'
      id-match: '*'
      user-agent: hello/1.0

    - name: local2
      url: http://localhost:3001/x/y/z
      profile-match: '*'
      id-match: '*'
      user-agent: hello/1.0
