
#
# Web (expressjs) settings.
#
web:
  port: 7000
  api: [3, 1]
  upload_storage: memory
  upload_path: "{{work_dir}}/web/upload/{{process_name}}"

#
# DO NOT USE any handlebars template variables (e.g. process_name) in logger
# section because they are never merged.
#
logger:
  rotating_file_stream:
    period: daily
    threshold: 1g     # The maximum size for a log file to reach before it's rotated.
    totalFiles: 60    # Keep 60 days (2 months) of log files.


#
# Transform from DGv1 schema (board_type/board_id/sensor: type) to
# DGv3 schema (p_type/p_id/s_type/s_id: {type1, type2, ...})
#
1to3:
  verbose: false


#
# Legacy REST api for TOE v1.0: `/api/v1/hub/:id/:profile` (POST)
#
webapi-legacy:
  enabled: false


#
# REST api endpoint to receive sensor data from HTTP forwarder of another
# instance of SensorHub.
#
webapi-hooks:
  enabled: true


#
# REST api endpoint to receive sensor data archive from devices with TOE3.0+.
#
webapi-upload:
  enabled: true
  # When timezone is not specified in query string, use this setting
  # as default value.
  timezone: Asia/Taipei


#
# Broker Manager, that manages multiple instances of brokers with different types.
#
#
broker-manager:
  verbose: false
  destinations:
    test0:
      type: file
      enabled: true
      verbose: false
      behaviors:
        health_check: false
        health_check_period: 60
        queue_if_unavailable: false
      filter:
        matched_profiles: '*'
        matched_ids: '*'
        matched_peripheral_types: '*'
        matched_sensor_types: '*'
      broker:
        path: "{{work_dir}}/web/brokers/test0"
        flush_threashold: 2

    test1:
      type: http
      enabled: true
      verbose: false
      behaviors:
        health_check: true
        health_check_period: 60
        queue_if_unavailable: false
      filter:
        matched_profiles: '*'
        matched_ids: '*'
        matched_peripheral_types: '*'
        matched_sensor_types: '*'
      broker:
        url: http://localhost:9998/x/y/z
        url_appending: true
        compressed: true
        snapshot: false
        health_checking_timeout: 5
        data_forwarding_timeout: 30
        request_opts:
          qs: {token: 'XXX'}

    test2:
      type: influxdb-1x-writer
      enabled: false
      verbose: false
      behaviors:
        health_check: false
        queue_if_unavailable: false
      filter:
        matched_profiles: '*'
        matched_ids: '*'
        matched_peripheral_types: '*'
        matched_sensor_types: '*'
      broker:
        url: http://localhost:8086
        username: root
        password: root



#
# Implement LINE-protocol (https://docs.influxdata.com/influxdb/v1.7/write_protocols/line_protocol_tutorial/)
# to write time-series data to InfluxDB v1.x, and also uses stats api (https://docs.influxdata.com/influxdb/v1.7/administration/server_monitoring/#show-stats)
# to check destination's health.
#
influxdb-1x-writer:
  verbose: false
  destinations:
    - name: test1
      enabled: true
      url: http://localhost:8086
      filter:
        matched_profiles: '*'
        matched_ids: '1803S320005[0-9]'
        matched_peripheral_types: '*'
        matched_sensor_types: '*'
      health_check: true
      opts: {}

    - name: test2
      enabled: false
      url: https://ifdb991.cestec.jp
      filter:
        matched_profiles: '*'
        matched_ids: '1803S320005[0-9]'
        matched_peripheral_types: '*'
        matched_sensor_types: '*'
      health_check: true
      opts: {}
